### ISSUE TITLE
"file" event never fired if one of the previous middlewares are async 

### ISSUE THREAD

**Issue by gs-akhan** [mscdex/busboy#112] opened 2016-02-27 11:55 UTC
Hi,
I am badly stuck into this issue. Instead on writing tons of paras, I better explain the code 

```
//midle2 is a database query - Async stuff
app.use(middlq1, middle2);
app.use(fileUpload);
```

If I remove `middle2` every thing works fine, even the "file" event is fired as expect. But if I add middleware which has async stuff - It doesn't work. 

To narrow it down, this is what my middle2 looks like .. 

```
function middle2(req, res, next) {
setTimeout(function() {
next();
});
}
```
Thanks in advance

**Comment by mscdex** [comment] 2016-02-27 20:25
`busboy` itself has nothing to do with middleware. If you're not seeing `file` events, then something else has switched the request stream into flowing mode, because initially streams are paused in node v0.10+ so as not to lose data (which seems to be what you're describing).

**Comment by gs-akhan** [comment] 2016-02-28 09:49
So you mean to say, after v0.10+ the req stream will be paused until the event handlers are attached ?
I am on v4.X.X though ..  But a simple setTimeout in a middleware is also making this issue.

Is there a way you can suggest to get over this. ?
Thanks

**Comment by mscdex** [comment] 2016-02-28 10:07
What you might try is eliminating other middleware (that come before the `busboy`-utilizing middleware) one-by-one to see which one is reading from the request stream.

**Comment by Basya-Zp** [comment] 2016-05-17 16:42
Hello guys, 

were you able to resolve the issue. Because I've got the same problem now. 

There is the list of middlewares to handle before I can accept files.

`router.post('/users/:id/profile-photo', authRequest, userController.uploadProfilePhoto);
`

I've just copied the first example from this page https://github.com/mscdex/busboy in my controller.

```
busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
      console.log('File [' + fieldname + ']: filename: ' + filename + ', encoding: ' + encoding + ', mimetype: ' + mimetype);
      file.on('data', function(data) {
        console.log('File [' + fieldname + '] got ' + data.length + ' bytes');
      });
      file.on('end', function() {
        console.log('END');
      });
    });
    busboy.on('field', function(fieldname, val, fieldnameTruncated, valTruncated, encoding, mimetype) {
      console.log('FIELD');
    });
    busboy.on('finish', function() {
      console.log('Done parsing form!');
    });
    req.pipe(busboy);
```

It doesn't fire 'file' even unfortunately and I could get just 'finish' one.

In this case I decided to use event emitter to pipe when I need this, so I created the following flow:

```
events.on('incomingPhoto', function() {
      req.pipe(busboy);
    });
```

Here in the same controller I have added this string to emit 'incomingPhoto' event:

```
events.emit('incomingPhoto');
```

I thought that this way could work. But I couldn't get it working due to the async middleware in my route flow.

Could you please check the issue and let me know if there is some solution or recommendation. Because for now I can just move busboy handler to accept photos before I run my middlewares. I don't want to do this due to the security reason.

Thank you in advance.

**Comment by mscdex** [comment] 2016-05-17 16:46
@Basya-Zp Well, is `authRequest` reading data from `req`? Most middleware that read request data don't pass control on until all of the data has been read, meaning there is no data left to read for any other middleware that also read request data.

**Comment by Basya-Zp** [comment] 2016-05-17 16:58
@mscdex 

I think there are no problems with 'authRequest' because it doesn't even work with setTimeout();

I mean the following code:

```
router
    .post('/users/:userId/profile-photo', (req, res, next) => {
      setTimeout(() => {
        next();
      }, 10);
    }, userController.uploadProfilePhoto);
```

If I remove setTimeout and leave just next() it works fine.

**Comment by mscdex** [comment] 2016-05-17 17:05
@Basya-Zp What node version are you using?

**Comment by Basya-Zp** [comment] 2016-05-17 20:30
@mscdex 

Node v5.10.0

**Comment by mscdex** [comment] 2016-05-17 21:13
@Basya-Zp I dunno then, there must still be some other middleware up the chain that is causing the request stream to flow. My suggestion is the same though: start eliminating middleware until the problem goes away (even keeping that `setTimeout()` middleware in place temporarily). All streams since node v0.10 start in a paused state, so there is *something* causing the stream to flow (either via `req.read()` or `req.on('data', ...)` or `req.resume()`).

**Comment by Basya-Zp** [comment] 2016-05-18 11:10
@mscdex 

Just fixed the issue by stopping and resuming my stream.

Added

```
req.pause();
```
before _authRequest_
and
```
req.resume();
```
in my controller

Thank you for your support.

**Comment by sudhirbitsgoa** [comment] 2016-09-07 14:01
Hi,
I'm also facing the same issue
If i remove all middlewares it works fine.
Only finish event is triggered and on file event is not triggered.
Please suggest

**Comment by mscdex** [comment] 2016-09-07 14:29
@sudhirbitsgoa If you remove all other middleware and it works, then one of those other middleware are reading from the request stream. Busboy cannot emit files/fields if there is nothing left to parse...

**Comment by Basya-Zp** [comment] 2016-09-08 17:13
@sudhirbitsgoa 

The problem was related to the fact that one of my middlewares was working out of the main stream. That's why I was forced to stop the stream. 

I recommend you doing the same thing. 
Just check middlewares one by one to identify the one you have the issue with and if it's possible, you may stop request stream, pass the middleware and resume it then.

**Comment by sudhirbitsgoa** [comment] 2016-09-08 17:25
I was using swagger https://github.com/swagger-api/swagger-editor
One of its middleware is loading routes. When this one is commented it works. The middleware is blackbox for me.
Any how i have moved my routes top of routes middleware as hack. req.pause did not help me either.
Thanks for your response.

**Comment by mscdex** [comment] 2016-10-02 21:23
Closing this for now, if someone can provide a minimal example (without other third party middleware) that reproduces this behavior, let me know.

**Closed by mscdex** 2016-10-02 21:23 UTC
