### ISSUE TITLE
Feature Request: Exposed Bytes-So-Far

### ISSUE THREAD

**Issue by bathos** [mscdex/busboy#69] opened 2015-02-02 04:43 UTC
Busboy's FileStream keeps track of the size-so-far of the data belonging to that portion of the multipart form data. As far as I can tell, though, it doesn't keep track of the total size of the payload, nor does it seem to expose either.

There's a good use case for this info, though. Say you have a form that you know has four fields, the last of which is a file. You can usually see the total size from the Content-Length header, but this includes everything, not just the file. By keeping track of the size-so-far, when we reach the file we can immediately check if the file is too large by subtracting the size-so-far from the Content-Length. That allows us to know the file is too large *before* consuming it instead of finding out later when the limit is reached. (And I suppose it would also allow us to calculate upload progress more accurately.)

Of course this info is a lot less useful for multi-file forms. It requires foreknowledge of the form's form to be used, so it's not like Busboy can actually emit an event or anything saying "file size exceeds limit"; the best that can be done is just to provide a raw number. What are your thoughts on this? Does exposing the bytesSoFar (or, alternatively, bytesRemaining) seem in keeping with Busboy's vision, or am I going too far out on a limb here?

**Comment by mscdex** [comment] 2015-02-02 05:40
The problem is that `Content-Length` is optional when chunked encoding is used and in some cases of broken clients, `Content-Length` can be unreliable. For these reasons, busboy does not bother looking for that header and pays attention to the content only instead.

I suppose a `bytesReceived` property could be added that simply contains the number of bytes currently written to the busboy instance, but that's a pretty trivial thing that could be just as easily done outside of the module too. I'm not sure how useful this number is though, unless maybe `Content-Length` *is* given and *is* accurate.

**Comment by bathos** [comment] 2015-02-02 06:31
You're right, on further investigation I'm finding it too unpredictable as to whether a file gets sent chunked or not -- I'm not even sure if this is something the client has control over typically. I did write my own little stream to count bytes before piping them into busboy, but I figured since busboy is already counting (but not exposing it), it felt redundant. My current file size solution is to send it as a field value (since HTML5 File objects have a size property).

**Comment by George02** [comment] 2015-04-25 10:19
@bathos so if you have multiple file upload form you create multiple `<input type="text" name="fileName" value="fileSize" hidden>` ? Then how do you get those values in `busboy.on('file')` event ?

**Comment by mscdex** [comment] 2015-04-25 13:09
@George02 Place them *before* your file fields and you will get the `field` event before the `file` event.

**Comment by George02** [comment] 2015-04-25 15:20
Yup. That's what I did. Also I created only one `<input>` with `value="fileName1=size;fileName2=size"` and parse it on the server side.

**Comment by bathos** [comment] 2015-04-25 15:21
@George02 -- yes, although I don't bother with actual hidden inputs; I examine the File object to discover the size and then assemble the formdata for submission without bothering with an actual form. And like mscdex said, sequence is preserved so you take that into account. For the server side I made a little Promise wrapping function that resolves on discovering a given field, used like `busboyField(busboy, fieldName, validate)`, so when handling the data I can do `Promise.all([bbfield1, bbfield2, bbfield3]).then(...).catch(...)` to help deal with the fact that I need to ensure I have certain fields before I can process the file; I think this pattern could be adapted for use with multiple files, too.

**Comment by George02** [comment] 2015-04-25 15:51
So now that I know the file size I can calculate the progress in the `file.on('data')` event. But how can I expose the progress to client ? Can you guys guide me to a tutorial or something ? My idea was to create a new GET route something like `/upload?fileName=myFile.txt` that will respond with a JSON containing the progress value and other info and from the client do ajax request in a `setInterval` function but I don't know how to implement this in my app. In expressjs can I create a new route at runtime ?

**Comment by mscdex** [comment] 2015-11-15 16:48
Closing this for now as I see no foolproof solution to the original request due to the nature of multipart requests. If you believe otherwise, let me know.

**Closed by mscdex** 2015-11-15 16:48 UTC
