### ISSUE TITLE
encoding issue

### ISSUE THREAD

**Issue by aniltomar10** [mscdex/busboy#187] opened 2018-11-17 00:09 UTC
I am uploading csv file from angular using form-data.  In my API I am using busboy to read file and csvtojson module to convert stream to json. It is working fine but when I upload a csv file with string "hÃ o",  busboy file event shows encoding "7bit" and json conversion string as "hào".

before converting stream to json if I use "file.setEncoding('latin1')" , JSON conversion is fine.

what should I do?

**Comment by mscdex** [comment] 2018-11-17 02:58
File data is transferred as-is from the source, so if there are any issues with the data itself, then that's an issue with the client (e.g. browser).

When your file data is text, you have to be aware of two things:

1. Text encoding - for file fields, the encoding value passed to `'file'` event handlers is typically meaningless, so it is important to know what encoding you're expecting. For JSON, this *should* be UTF-8. If a client is sending JSON using any other encoding, I would consider that client to be broken.

2. Concatenating text of a multi-byte encoding. Since file data is represented by a node stream and passes data as-is, you have to be careful with how you interpret the underlying file data if multi-byte characters are possible. This means you cannot simply do something like:

   ```js
   var buf = '';
   file.on('data', (chunk) => { buf += chunk; });
   file.on('end', () => {
     // use `buf`
   });
   ```

   because if `chunk` ends on (say byte 1 of 3 of) a partial character, `buf` will instead contain a UTF-8 replacement character representing the broken character.

   To prevent this issue, you can use `file.setEncoding()` (a method built-in to all node streams) to take care of these multi-byte issues for you and will then emit strings instead of `Buffer`s. So for example, simply adding `file.setEncoding('utf8')` before `file.on('data', ....)` in the previous example is all that is needed. The alternative would be to collect the `Buffer` chunks as-is, combine them into one larger buffer (e.g. using `Buffer.concat()`), and *then* calling `entireBuffer.toString('utf8')`. However calling `file.setEncoding()` is a lot simpler.

**Comment by charmander** [comment] 2018-11-17 04:46
> because if `chunk` ends on (say byte 1 of 3 of) a partial character, `buf` will instead contain a UTF-8 replacement character representing the broken character.

That can’t happen on a Node readable stream yielding strings, can it? [Stream documentation][1]:

> The `Readable` stream will properly handle multi-byte characters delivered through the stream that would otherwise become improperly decoded if simply pulled from the stream as `Buffer` objects.

  [1]: https://nodejs.org/api/stream.html#stream_readable_setencoding_encoding

**Comment by aniltomar10** [comment] 2018-11-19 22:57
I am not using file.on('data') event.  This is how I am using busboy.
Inside API route I have this code:
var busboy = new Busboy({ headers: req.headers });
 busboy.on('file', function (fieldname, fileStream, filename, encoding, mimetype) {
//here converting fileStream to json 
fileStream.pipe(csvToJson()).then((jsonObj) => {console.log(jsonObj)});


Before converting to json if I use fileStream.setEncoding('utf8'), json still show incorrect data but if I use fileStream.setEncoding('latin1'), json shows correct data.

From client (browser) I am uploading file with 'utf8' encoding.

**Comment by mscdex** [comment] 2018-11-20 01:40
Then the issue is either the client is somehow sending malformed data *or* there is an issue with `csvToJson()`'s implementation. `busboy` literally just passes the bytes on through from the client without modifying anything.

**Closed** 2021-12-19 20:07 UTC
