### ISSUE TITLE
Add a stop or abort method

### ISSUE THREAD

**Issue by imns** [mscdex/busboy#81] opened 2015-06-10 14:53 UTC
Right now the only way I have found to stop a file form uploading is to call `busboy._parser.parser._ignore()`.  It would be great if you exposed some sort of abort method.

Use case: you want to do some validation on the image, but as soon as the image is not valid, stop uploading the image and return the error to the client.  If you're uploading a 1 gig image and you can figure out 1/4 of the way through parsing it that it's the wrong width then it's much better to stop then as opposed to making the user wait until `finish` event is called.

Example pseudoish code of I'd like to do: 
```
if (self.req.method === 'POST') {
    var busboy = this.busboy = new Busboy({
        headers: self.req.headers
    });

    busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
        file.on('data', function(data) {

            if(IMAGE IS THE WRONG WIDTH) {
                busboy.abort();
            }

            if(IMAGE IS THE WRONG DPI) {
                busboy.abort();
            }

            if(IMAGE IS THE WRONG SOMETHING ELSE) {
                busboy.abort();
            }

        });
    });

    busboy.on('aborted', function() {
        // DO SOMETHING HERE ... maybe return error to the client
    });
}
```

**Comment by mscdex** [comment] 2015-06-10 15:06
What about doing `file.resume();` and letting the data drain out that way?

**Comment by mscdex** [comment] 2015-06-10 15:07
I'd be open to a PR to add an `abort()` method for draining the rest of all other form data parts though.

**Comment by mscdex** [comment] 2015-07-03 15:27
A better solution though to avoid processing unnecessary data might be to do something like:

```javascript
self.req.unpipe(busboy);
self.res.statusCode = 400;
self.res.end();
```

**Comment by Kikketer** [comment] 2015-09-24 14:32
@mscdex I've tried what you have written, but the res.end bit does not return out of the server since the `req.pipe(busboy)` is set up.  I realize this may be a basic question, I've just not messed with pipes and breaking the pipes all that often.

The psudocode above makes sense in my head, "on an error send something to the client".  But the end of my function has `return req.pipe(busboy)`.  Regardless of the error, and when I unpipe busboy from the request, I still get a 200 back from the server.

**Comment by mscdex** [comment] 2015-09-24 14:46
@Kikketer You'll have to provide a reproducible example, as it's hard to tell what could be wrong otherwise.

**Comment by Kikketer** [comment] 2015-09-24 15:09
@mscdex So this is what I have:
````
    var busboy = new Busboy({
      headers: req.headers,
      limits: {
        files: 1,
        fileSize: 1024
      }
    });
    var saveTo = path.join(__dirname, '../teamPhotos', req.params.id + '.jpg');

    busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
      file.on('limit', function() {
        console.log('limit reached!');
        req.unpipe(busboy);
        res.status(500).end('Limit Reached');  // Not doing anything...
      });
      file.pipe(fs.createWriteStream(saveTo));
    });
    busboy.on('finish', function() {
       res.writeHead(200, {'Connection': 'close'});
       res.end();
    });

    // This doesn't work without piping here, but also always returns 200
    return req.pipe(busboy);
````

**Comment by mscdex** [comment] 2015-10-02 05:38
Ah yeah, if the client is expecting the connection to be kept alive, sending a response works fine, but the current request data would need to be drained first. Setting `Connection: close` is probably the best solution here when hitting a configured resource limit like this, to avoid transferring unwanted data.

**Closed by mscdex** 2015-10-02 05:38 UTC

**Comment by RomanBurunkov** [comment] 2019-11-21 08:37
Hi @mscdex 

Is such method to abort upload still applicable?
I've done some testing and found out that if file size is quite small(0-150kb for tests in local network) uploading process doesn't abort.

In the same time if file about 250 kb it works fine.

I run upload and check the mime type and if it is not supported I closed connection in this way

```
  // Close connection with specified reason and http code, default: 400 Bad Request.
  const closeConnection = (code, reason) => {
    req.unpipe(busboy);
    res.writeHead(code || 400, { Connection: 'close' });
    res.end(reason || 'Bad Request');
  };
```

So it looks that for small files even if busboy unpiped and connection closed, it still triggers all files handlers: data, end and so on and also busboy event 'finish'.

**Comment by FabioZan86** [comment] 2025-04-03 11:36
> A better solution though to avoid processing unnecessary data might be to do something like:
> 
> self.req.unpipe(busboy);
> // `Connection: close` is important here, to ensure the socket is closed after
> // we write our response.
> self.res.writeHead(400, { 'Connection': 'close' });
> self.res.end();

`file.removeAllListeners()` was the key to completely stopping the file's event stream, ensuring that no further events were processed. This prevents the busboy from continuing to read, and prevents the server from waiting for the stream to finish.

```
file.on('limit', function() {
        console.log('limit reached!');
        file.removeAllListeners()
        res.status(500).end('Limit Reached');  // Not doing anything...
      });
```

```
  file.on('data', (data) => {  
      totalBytes += data.length;
      if (totalBytes > 5242880) { //  5 MB
        file.resume();
        file.removeAllListeners();
        file.unpipe();
        busboy.removeAllListeners();
        res.status(500).end('Limit Reached'); 
    }
});
```

with `file.removeAllListeners()` no matter how big the file is, the end event is never triggered!
